config/routes.rb
BackboneOnRails::Application.routes.draw do
  resources :items

  root :to => 'items#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :description, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<script type="text/template" id="create_item_template">
  <label>New Item: </label>
  name <input type="text" id="name_input" />
  description <input type="text" id="description_input" />
  <input type="button" id="create_button" value="Create" />
</script>

<script type="text/javascript">
ItemModel = Backbone.Model.extend({
    urlRoot: '/items',
    defaults: {
        name: '',
        description: '',
    },
    toFullJSON: function() {return JSON.stringify(this.toJSON()); },
});

ItemCollection = Backbone.Collection.extend({
  model: ItemModel,
  toFullJSON: function() {
    return this.map(function(model){ return model.toFullJSON(); });
  },
});

ItemView = Backbone.View.extend({
  tagName: 'li',
  events: {
    'click span.delete': 'remove',
  },
  initialize: function() {
    _.bindAll(this, 'render', 'unrender', 'remove') // every function that uses 'this' as the current object should be in here
    this.model.change('change', this.render);
    this.model.bind('remove', this.unrender);
  },
  render: function() {
    $(this.el).html('Name: '+this.model.get('name')+' description: '+this.model.get('description')
                     +' <span class="delete" style="cursor:pointer; color:red; font-family:sans-serif;">[delete]</span>');
    return this;// for chainable calls, like .render().el
  },
  unrender: function() {
    $(this.el).remove();
  },
  remove: function() {
    this.model.destroy();
  },
});

ListView = Backbone.View.extend({
  el: $('body'),
  events: {
      'click #create_button': 'doCreateItem',
  },
  initialize: function(){
    _.bindAll(this, 'render', 'doCreateItem', 'appendItem'); // every function that uses 'this' as the current object should be in here
    
    this.collection = new ItemCollection();
    this.collection.bind('add', this.appendItem); // collection event binder

    this.counter = 0;
    this.render();
  },
  render: function(){
    var self = this;
    var template = _.template( $("#create_item_template").html(), {} );
    $(this.el).append(template);
    $(this.el).append("<ul></ul>");
    _(this.collection.models).each(function(item){ // in case collection is not empty
      self.appendItem(item);
    }, this);
  },

  doCreateItem: function() {
    // Button clicked, you can access the element that was clicked with event.currentTarget
    var item = new ItemModel();
    var self = this;
    item.save({name: $("#name_input").val(), description: $("#description_input").val()},
      {success: function (item) {
          self.collection.add(item);
      }
    });
    // // Another way of pass this to callback function
    // item.save({name: $("#name_input").val(), description: $("#description_input").val()},
    //   {success: function (item) {
    //       this.collection.add(item);
    //   }.bind(this)      
    // });
  },
  appendItem: function(item){
    var itemView = new ItemView({
      model: item
    });
    $('ul', this.el).append(itemView.render().el);
  }
});

var listView = new ListView();
var itemList = new ItemCollection();
itemList.fetch({url:'/items.json',
  success: function(itemList) {
    itemList.each(function(model){
      listView.appendItem(model);
    });
  }
});
</script>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @item.name %>
</p>

<p>
  <b>Description:</b>
  <%= @item.description %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BackboneOnRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>